### ISSUE TITLE
Package Update Problem

### ISSUE THREAD

**Issue by programlayan** [Greg798100/orange-pi-r1#1]
Hello,
I installed your image to R1, thank you everything is working.
But, I tried to install zerotier package:
--- output ---
Installing zerotier (1.2.12-3) to root...
Downloading http://downloads.openwrt.org/releases/18.06.8/packages/arm_cortex-a7_neon-vfpv4/packages/zerotier_1.2.12-3_arm_cortex-a7_neon-vfpv4.ipk
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for zerotier:
 * 	kernel (= 4.14.171-1-275eeaac3d4bfc187027feeafed7b291)
 * opkg_install_cmd: Cannot install package zerotier.
----
I could not install kmod-tun package also, required for VPN connections.
How can I install this package?
Thank you.

**Comment by Greg798100** [comment]
Hi.
Not included libraries, just to rebuild from source with the libraries included.
_libc, libssp, libpthread_

**Comment by Greg798100** [comment]
>  zerotier

Hi.
Not included libraries, just to rebuild from source with the libraries included.
_libc, libssp, libpthread_

Download https://github.com/openwrt/openwrt/releases  v18.06.8
Download https://github.com/jayanta525/openwrt-opiR1/tree/master/package/kernel/rtl8189es and copy rtl8189es to  v18.06.8
Config your and build.

**Comment by programlayan** [comment]
Thank you I will try it..

**Comment by Greg798100** [comment]
update repo

**Comment by programlayan** [comment]
Thank you for your good job 👍
